-- 146_clock_adjustment_requests.sql
-- Timeclock adjustment requests: employees who forgot to clock in/out (or
-- were auto-clocked-out) can request a time fix on one of their own clock
-- events; reviewers approve or decline from a new Adjustments sub-tab on
-- the Clock page.
--
-- Who can review:
--   * admins / developers                          -> all requests in org
--   * clock viewers (can_view_clock_comparison)    -> per clock_view_scope:
--       'all'      -> all requests in org
--       'managed'  -> only requests from employees in departments the
--                     viewer manages (departments.manager_id = viewer)
--
-- On approval the clock event's occurred_at is set to the requested time
-- and auto_closed is cleared (a human has now vouched for the time), so
-- every report computed from clock_events picks the fix up automatically.
--
-- clock_events has admin-only RLS, so employees read their own events via
-- the list_my_clock_events RPC below.
--
-- Safe to re-run.

create table if not exists public.clock_adjustment_requests (
    id               bigint generated by default as identity primary key,
    organisation_id  bigint not null references public.organisations (id) on delete cascade,
    user_id          bigint not null references public.users (id) on delete cascade,
    clock_event_id   bigint not null references public.clock_events (id) on delete cascade,
    -- Snapshots at request time, so the request stays legible even after
    -- the event is adjusted (or a second adjustment happens later).
    event_type       text not null,
    original_time    timestamptz not null,
    requested_time   timestamptz not null,
    reason           text,
    status           text not null default 'pending'
                     check (status in ('pending', 'approved', 'declined')),
    reviewed_by      bigint references public.users (id) on delete set null,
    review_note      text,
    reviewed_at      timestamptz,
    created_at       timestamptz not null default now()
);

-- One open request per clock event at a time.
create unique index if not exists clock_adjustment_pending_uq
    on public.clock_adjustment_requests (clock_event_id)
    where (status = 'pending');

create index if not exists clock_adjustment_org_status_idx
    on public.clock_adjustment_requests (organisation_id, status, created_at);

alter table public.clock_adjustment_requests enable row level security;

-- Admins manage everything directly; employees can read their own rows
-- (for the "my requests" list) and delete their own while still pending
-- (cancel). Insert and review go through the SECURITY DEFINER RPCs.
do $$
begin
    if not exists (select 1 from pg_policies
                    where schemaname = 'public' and tablename = 'clock_adjustment_requests'
                      and policyname = 'admins manage clock_adjustment_requests') then
        execute $policy$
            create policy "admins manage clock_adjustment_requests"
              on public.clock_adjustment_requests for all to authenticated
              using (is_admin_of(organisation_id))
              with check (is_admin_of(organisation_id))
        $policy$;
    end if;
    if not exists (select 1 from pg_policies
                    where schemaname = 'public' and tablename = 'clock_adjustment_requests'
                      and policyname = 'employees read own clock_adjustment_requests') then
        execute $policy$
            create policy "employees read own clock_adjustment_requests"
              on public.clock_adjustment_requests for select to authenticated
              using (exists (select 1 from public.users u
                              where u.id = clock_adjustment_requests.user_id
                                and u.auth_user_id = auth.uid()))
        $policy$;
    end if;
    if not exists (select 1 from pg_policies
                    where schemaname = 'public' and tablename = 'clock_adjustment_requests'
                      and policyname = 'employees delete own pending clock_adjustment_requests') then
        execute $policy$
            create policy "employees delete own pending clock_adjustment_requests"
              on public.clock_adjustment_requests for delete to authenticated
              using (status = 'pending'
                     and exists (select 1 from public.users u
                                  where u.id = clock_adjustment_requests.user_id
                                    and u.auth_user_id = auth.uid()))
        $policy$;
    end if;
end$$;

grant select, delete on public.clock_adjustment_requests to authenticated;

-- ------------------------------------------------------------------
-- list_my_clock_events(p_start, p_end_excl)
--   The caller's own clock events in [p_start, p_end_excl), plus the id
--   of any pending adjustment request against each event so the UI can
--   show "requested" instead of another Request button.
-- ------------------------------------------------------------------
create or replace function public.list_my_clock_events(
    p_start    timestamptz,
    p_end_excl timestamptz
)
returns table (
    id                 bigint,
    event_type         text,
    occurred_at        timestamptz,
    source             text,
    auto_closed        boolean,
    pending_request_id bigint
)
language plpgsql stable security definer set search_path = public
as $$
declare
    v_me public.users%rowtype;
begin
    select * into v_me from public.users where auth_user_id = auth.uid();
    if v_me.id is null then
        raise exception 'No employee record for this account';
    end if;

    return query
    select ce.id, ce.event_type, ce.occurred_at, ce.source, ce.auto_closed,
           pr.id as pending_request_id
      from public.clock_events ce
      left join lateral (
          select r.id from public.clock_adjustment_requests r
           where r.clock_event_id = ce.id and r.status = 'pending'
           limit 1
      ) pr on true
     where ce.user_id = v_me.id
       and ce.occurred_at >= p_start
       and ce.occurred_at <  p_end_excl
     order by ce.occurred_at;
end$$;

grant execute on function public.list_my_clock_events(timestamptz, timestamptz) to authenticated;

-- ------------------------------------------------------------------
-- submit_clock_adjustment(p_clock_event_id, p_requested_time, p_reason)
--   Employee files a fix request against one of their OWN clock events.
--   Requested time must differ from the recorded time and stay within
--   24h of it (sanity bound; auto-closed events can be hours off but
--   never a day off).
-- ------------------------------------------------------------------
create or replace function public.submit_clock_adjustment(
    p_clock_event_id bigint,
    p_requested_time timestamptz,
    p_reason         text default null
)
returns bigint
language plpgsql security definer set search_path = public
as $$
declare
    v_me public.users%rowtype;
    v_ev public.clock_events%rowtype;
    v_id bigint;
begin
    select * into v_me from public.users where auth_user_id = auth.uid();
    if v_me.id is null then
        raise exception 'No employee record for this account';
    end if;

    select * into v_ev from public.clock_events
     where id = p_clock_event_id and user_id = v_me.id;
    if v_ev.id is null then
        raise exception 'Clock event not found';
    end if;

    if p_requested_time is null then
        raise exception 'Requested time is required';
    end if;
    if p_requested_time = v_ev.occurred_at then
        raise exception 'Requested time is the same as the recorded time';
    end if;
    if abs(extract(epoch from (p_requested_time - v_ev.occurred_at))) > 86400 then
        raise exception 'Requested time must be within 24 hours of the recorded time';
    end if;
    if exists (select 1 from public.clock_adjustment_requests r
                where r.clock_event_id = p_clock_event_id and r.status = 'pending') then
        raise exception 'There is already a pending request for this clock event';
    end if;

    insert into public.clock_adjustment_requests
        (organisation_id, user_id, clock_event_id, event_type,
         original_time, requested_time, reason)
    values
        (v_ev.organisation_id, v_me.id, p_clock_event_id, v_ev.event_type,
         v_ev.occurred_at, p_requested_time,
         nullif(trim(coalesce(p_reason, '')), ''))
    returning id into v_id;

    return v_id;
end$$;

grant execute on function public.submit_clock_adjustment(bigint, timestamptz, text) to authenticated;

-- ------------------------------------------------------------------
-- list_clock_adjustment_requests(p_org_id, p_status)
--   Reviewer's list. p_status null = all statuses. Scope enforced
--   server-side per the rules at the top of this file.
-- ------------------------------------------------------------------
create or replace function public.list_clock_adjustment_requests(
    p_org_id bigint,
    p_status text default null
)
returns table (
    id              bigint,
    user_id         bigint,
    employee_name   text,
    department_name text,
    clock_event_id  bigint,
    event_type      text,
    original_time   timestamptz,
    requested_time  timestamptz,
    reason          text,
    status          text,
    review_note     text,
    reviewed_at     timestamptz,
    created_at      timestamptz
)
language plpgsql stable security definer set search_path = public
as $$
declare
    v_caller public.users%rowtype;
    v_all    boolean := false;
begin
    if public.is_admin_of(p_org_id) or public.is_developer() then
        v_all := true;
    else
        select * into v_caller from public.users
         where auth_user_id = auth.uid() and organisation_id = p_org_id;
        if v_caller.id is null or not v_caller.can_view_clock_comparison then
            raise exception 'Not authorised to review clock adjustments';
        end if;
        if coalesce(v_caller.clock_view_scope, 'all') = 'all' then
            v_all := true;
        end if;
    end if;

    return query
    select r.id, r.user_id, u.name, d.name,
           r.clock_event_id, r.event_type, r.original_time,
           r.requested_time, r.reason, r.status,
           r.review_note, r.reviewed_at, r.created_at
      from public.clock_adjustment_requests r
      join public.users u on u.id = r.user_id
      left join public.departments d on d.id = u.department_id
     where r.organisation_id = p_org_id
       and (p_status is null or r.status = p_status)
       and (v_all or u.department_id in
             (select dd.id from public.departments dd
               where dd.organisation_id = p_org_id
                 and dd.manager_id = v_caller.id))
     order by r.created_at;
end$$;

grant execute on function public.list_clock_adjustment_requests(bigint, text) to authenticated;

-- ------------------------------------------------------------------
-- review_clock_adjustment(p_request_id, p_approve, p_note)
--   Approve (applies the fix to clock_events, clears auto_closed) or
--   decline. Same permission + scope rules as the list RPC, re-checked
--   against the request's target user so a managed-scope viewer can't
--   review a request they can't see.
-- ------------------------------------------------------------------
create or replace function public.review_clock_adjustment(
    p_request_id bigint,
    p_approve    boolean,
    p_note       text default null
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
    v_req     public.clock_adjustment_requests%rowtype;
    v_target  public.users%rowtype;
    v_caller  public.users%rowtype;
    v_allowed boolean := false;
begin
    select * into v_req from public.clock_adjustment_requests
     where id = p_request_id
     for update;
    if v_req.id is null then
        raise exception 'Request not found';
    end if;
    if v_req.status <> 'pending' then
        raise exception 'Request has already been reviewed';
    end if;

    select * into v_target from public.users where id = v_req.user_id;

    if public.is_admin_of(v_req.organisation_id) or public.is_developer() then
        v_allowed := true;
    else
        select * into v_caller from public.users
         where auth_user_id = auth.uid()
           and organisation_id = v_req.organisation_id;
        if v_caller.id is not null and v_caller.can_view_clock_comparison then
            if coalesce(v_caller.clock_view_scope, 'all') = 'all' then
                v_allowed := true;
            else
                v_allowed := exists (
                    select 1 from public.departments d
                     where d.organisation_id = v_req.organisation_id
                       and d.manager_id = v_caller.id
                       and d.id = v_target.department_id);
            end if;
        end if;
    end if;
    if not v_allowed then
        raise exception 'Not authorised to review this request';
    end if;

    if p_approve then
        update public.clock_events
           set occurred_at = v_req.requested_time,
               auto_closed = false
         where id = v_req.clock_event_id;
        if not found then
            raise exception 'The clock event no longer exists';
        end if;
    end if;

    update public.clock_adjustment_requests
       set status      = case when p_approve then 'approved' else 'declined' end,
           reviewed_by = (select u.id from public.users u
                           where u.auth_user_id = auth.uid()
                             and u.organisation_id = v_req.organisation_id),
           review_note = nullif(trim(coalesce(p_note, '')), ''),
           reviewed_at = now()
     where id = p_request_id;
end$$;

grant execute on function public.review_clock_adjustment(bigint, boolean, text) to authenticated;
