-- 153_record_scan_early_leave_window.sql — WITHDRAWN, never applied.
--
-- This migration originally recreated the kiosk's record_scan with a
-- widened shift-end window (lower edge 7h30m). Withdrawn after
-- coordinating with the Attendium (kiosk) repo, which owns the
-- record_scan write path:
--
--   - The agreed bound is 7h50m (±10m around the sanctioned 8h00m
--     early departure), not 7h30m — 7h30m would have created a
--     55-minute silent-clock-out band that swallows the final-break
--     menu option and erases the early-leaver signal.
--   - The change is authored as Attendium migration 212 (their repo's
--     numbered history is authoritative for record_scan and
--     record_offsite_choice), together with server-side classification
--     in record_offsite_choice so the menu's "Clock out" only records
--     clocked_out_early when the departure is genuinely early.
--   - Ownership rule going forward: Attendium owns the kiosk write
--     path; Timeium owns the read/report functions (_offsite_report,
--     _timesheet_rows, org_live_status) — see migration 154, which
--     restores Attendium 208's off-site-personal logic that our
--     149/151 snapshots had silently reverted.
--   - Attendium reserves migration numbers 200+; Timeium stays within
--     031–199.
--
-- Intentionally a no-op. Safe to run; does nothing.

select 1;
